demonstration_mathdatasimplified:
  outputs:
    dev:
      dbname:
      - dbname
      host:
      - host
      pass:
      - dev_password
      port:
      - port
      schema:
      - dev_schema
      threads:
      - 1 or more
      type: postgres
      user:
      - dev_username
    prod:
      dbname:
      - dbname
      host:
      - host
      pass:
      - prod_password
      port:
      - port
      schema:
      - prod_schema
      threads:
      - 1 or more
      type: postgres
      user:
      - prod_username
  target: dev
rais:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
  target: dev
sql_jinja:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
  target: dev
test_dbt:
  outputs:
    dev:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
    prod:
      dbname: postgres
      host: localhost
      pass: '123'
      port: 5433
      schema: postgres
      threads: 1
      type: postgres
      user: postgres
  target: dev
version_project_20_3_2024:
  outputs:
    dev:
      dbname: q
      host: dbt_20_3_2024
      pass: '123'
      port: 5432
      schema: w
      threads: 1
      type: postgres
      user: deb_dbt_20_3_2024
  target: dev
