test_dbt:
  outputs:

    dev:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

    prod:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

  target: dev

sql_jinja:
  outputs:

    dev:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

    prod:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

  target: dev


rais:
  outputs:

    dev:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

    prod:
      type: postgres
      threads: 1 #[1 or more]
      host: localhost #[host]
      port: 5433 #[port]
      user: postgres #[dev_username]
      pass: '123' #[dev_password]
      dbname: postgres #[dbname]
      schema: postgres #[dev_schema]

  target: dev

  target: dev

demonstration_mathdatasimplified:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev

demonstration_mathdatasimplified:
  outputs:

    dev:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [dev_username]
      pass: [dev_password]
      dbname: [dbname]
      schema: [dev_schema]

    prod:
      type: postgres
      threads: [1 or more]
      host: [host]
      port: [port]
      user: [prod_username]
      pass: [prod_password]
      dbname: [dbname]
      schema: [prod_schema]

  target: dev
