version: 2
# resources of data for ingestion

sources:
  - name: source_parameter
    description: This my new one dbt creation from database running

    database: postgres
    #database: postgres

    schema: postgres
    #schema: public

    tables:
      - name: postal-code-germany
      - name: table_view_one