version: 2

sources:
  - name: testing
    description: database running
    database: postgres
    schema: public
    tables:
      - name: pokemon
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: name
            tests:
              - not_null
      #- name: customers

  #- name: stripe
  #  tables:
  #    - name: payments